name: Simulacion de Pruebas en PR

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # --- PRIMER CHECK ---
  pruebas-base-datos:
    name: "Check 1: Conectividad y Acceso"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Ejecutar Bloque 1
        run: node ${{ github.workspace }}/automated_Omega.js bloque1

  # --- SEGUNDO CHECK (Falla controlada) ---
  pruebas-rendimiento-api:
    name: "Check 2: Performance de API"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Ejecutar Bloque 2
        run: node ${{ github.workspace }}/automated_Omega.js bloque2

  # --- TERCER CHECK ---
  pruebas-archivos-media:
    name: "Check 3: Integridad de Archivos"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Ejecutar Bloque 3
        run: node ${{ github.workspace }}/automated_Omega.js bloque3
